# Generated by Django 2.2.4 on 2019-10-09 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('Text', models.TextField()),
                ('Date', models.DateTimeField(default=datetime.datetime.now, primary_key=True, serialize=False)),
            ],
        ),
    ]
